# Generated by Django 5.0.4 on 2024-04-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_judge_game_intro_game_outro_game_prize_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresponse',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
