# Generated by Django 5.0.4 on 2024-04-28 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_questionresponse_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='current_judge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.judge'),
        ),
    ]
